### ISSUE TITLE
Calling ds.store({ ... }) returns error

### ISSUE THREAD

**Issue by ofzza** [scotthovestadt/gigya#15]
Calling ```gigya.ds.store({ ... })``` returns error:

```
Gigya API ds.setSchema failed with error code 403005 and message Unauthorized user
```

**Comment by ofzza** [comment]
Seems the ```gigya.sds.store({...})``` method targets the wrong REST endpoint. It is targeting ```ds.setSchema``` instead of ```ds.store```.

Proposing a fix in PR #16. I've tested after changing the targeted endpoint and there are no fiurther problems ...

**Comment by scotthovestadt** [comment]
@ofzza Definitely my fault. Sorry about that and thanks for fixing it. I'll release a new version on NPM today.

**Comment by ofzza** [comment]
@scotthovestadt
Tnx for such a quick response and for all the great work!
