### ISSUE TITLE
Api calls not supporting promises.

### ISSUE THREAD

**Issue by singerxt** [scotthovestadt/gigya#3]
Hey! Thanks for all your hard work on writing Gigya wrapper for node.js ! :-)

I think will be good to support promises for example

``` javascript
gigya.socialize.getToken(params)
  .then(loginUser)
  .catch(errorHandler)
```

**Comment by scotthovestadt** [comment]
Yeah, I agree. I'd actually like to refactor this as a breaking change to be promises-only.

For now, you can use bluebird promisify to automatically convert to promises.

**Comment by scotthovestadt** [comment]
@singerxt 6 months later - I just released a new version that supports promises. It also has support for TypeScript definitions! (If you haven't tried TS, I recommend it. A lot.)
