### ISSUE TITLE
Unnecessary named with Unofficial Gigya JavaScript REST SDK  

### ISSUE THREAD

**Issue by MiguelSavignano** [scotthovestadt/gigya#33]
Hi I recomend remove the word Unofficial. This word scared some people.

You exaplain this in Usage.
```
This is an unofficial SDK for Gigya's REST API. Please do not contact Gigya support with questions or concerns about this SDK. For any issues, please make an issue on GitHub.
```
I know this package its't supporter by gigya support team.
You can explain this with others words like this.

```
This is an open source SDK for Gigya's REST API. Please do not contact Gigya support with questions or concerns about this SDK. For any issues, please make an issue on GitHub.
```

**Comment by scotthovestadt** [comment]
@iBaryo Baryo, what does Gigya think?

@MiguelSavignano I'd recommend making a PR with the proposal (since it's so simple).

**Comment by iBaryo** [comment]
i'm afraid supporting it officially by Gigya (SAP) has some legal implication, so it's not possible.

**Comment by iBaryo** [comment]
hi man! thx for caring!
we consulted about it internally and decided to keep it as it is in order to prevent confusion that might cause Gigya customers to open support tickets to them :)
