### ISSUE TITLE
signing requests for REST API calls

### ISSUE THREAD

**Issue by mpurusottamc** [scotthovestadt/gigya#36]
Currently, the REST API calls are not signed. Secret is sent as part of the payload.

**Comment by khaledosman** [comment]
same.. I'm getting Error: Gigya API accounts.getAccountInfo failed with error code 403003 and message Invalid request signature when following the example.. is there a way around this ?

**Comment by iBaryo** [comment]
fixed in the latest release - together with a JWT signed requests (auth bearer token) using the userkey's private key.
