### ISSUE TITLE
Login and Sign up with Line

### ISSUE THREAD

**Issue by andreyzenkov** [scotthovestadt/gigya#49]
Hi Guys! Please help or advice. I'm trying to add a new provider Line, configured Line in a gigya console under Providers Configurations section(App ID, Secret Access Key).  Using method with params gigya.accounts.socialLogin({provider: "line", keepLogged: true}). 

On click I see https://take.ms/WtURX, but when I'm typing a correct email and password always see the text *The email address or password you entered doesn't exist or is invalid. Please also ensure that you have enabled "Allow login" on your smartphone as shown below: Settings > Accounts > Allow login* 

Settings > Accounts > Allow login is active https://take.ms/eFtnq

https://take.ms/d40Ia Email and password are correct because I able to login with these credentials in Line mobile, desktop apps. 

Tried the same flow on package versions 3.0.1, 2.0.33. Please help.

**Comment by iBaryo** [comment]
hi andrey, this repo is for the backend nodejs sdk - i suggest contacting Gigya support for this issue.
