### ISSUE TITLE
Is this library abandoned?

### ISSUE THREAD

**Issue by gerardolima** [scotthovestadt/gigya#59]
First of all, thank you for the work done! This is a very comprehensive way to access Gigya library using TypeScript! 

Nevertheless, I noticed this project has no commits since August 2020 and some interfaces are outdated. Is there any intention to update this library to stay in synch with Gigya API?

**Comment by mirkogolze** [comment]
Hi,
we are using the library in production. It would be nice if the interfaces could be brought up to date.

**Comment by gerardolima** [comment]
@scotthovestadt, would you consider accepting pull requests?

**Comment by bmxpiku** [comment]
Well we ended up just making internal module with couple of copied interfaces from here :/ pity though, it was a nice work that was done here

**Comment by gerardolima** [comment]
Yes, this library is very well done, it's a pity this good work is abandoned.

**Comment by umbarov** [comment]
> Well we ended up just making internal module with couple of copied interfaces from here :/ pity though, it was a nice work that was done here

@bmxpiku Why not make it public? :)

**Comment by gerardolima** [comment]
closed due to no-response
